### ISSUE TITLE
Markdown breaks npm start

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#113]
Something about the `markdown-to-jsx` setup we have for the markdown files in `_post` is causing `npm start`/`npm run build` to error out.

```
➜  base2.io git:(next--design) ✗ npm run build
> next.base2.io@0.1.0 build /Users/chawkins/dev/base2.io
> next build && next export -o build
> Using external babel configuration
> Location: "/Users/chawkins/dev/base2.io/.babelrc"
  using build directory: /Users/chawkins/dev/base2.io/.next
  copying "static" directory
  exporting path: /blog/2011-08-26-open-for-business
  exporting path: /blog/2012-04-30-now-with-more-jekyll
  exporting path: /blog/2012-05-01-vagrants-and-chefs-and-librarians-oh-my
  exporting path: /blog/2012-11-30-seeding-with-progress
  exporting path: /blog/2013-08-23-startup-magnet-poetry
  exporting path: /blog/2013-10-18-karma-tests-circle-ci
  exporting path: /blog/2013-10-29-conditionally-mock-http-backend
  exporting path: /blog/2013-12-07-link-roundup-3
{ Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at instantiateReactComponent (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/instantiateReactComponent.js:74:250)
    at instantiateChild (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/ReactChildReconciler.js:44:28)
    at traverseAllChildrenImpl (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/traverseAllChildren.js:77:5)
    at traverseAllChildrenImpl (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/traverseAllChildren.js:93:23)
    at traverseAllChildrenImpl (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/traverseAllChildren.js:93:23)
    at traverseAllChildren (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/traverseAllChildren.js:172:10)
    at Object.instantiateChildren (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/ReactChildReconciler.js:74:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/ReactMultiChild.js:191:35)
    at ReactDOMComponent.mountChildren (/Users/chawkins/dev/base2.io/node_modules/react-dom/lib/ReactMultiChild.js:224:27) name: 'Invariant Violation', framesToPop: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next.base2.io@0.1.0 build: `next build && next export -o build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next.base2.io@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chawkins/.npm/_logs/2017-08-30T20_26_25_641Z-debug.log
```

**Comment by kalongthewires** [comment]
Switching over to Gatsby so this card will no longer be relevant.
